# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Projects\NLMDOF\ui\win_about.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_win_about(object):
    def setupUi(self, win_about):
        win_about.setObjectName("win_about")
        win_about.setWindowModality(QtCore.Qt.NonModal)
        win_about.resize(650, 300)
        win_about.setMinimumSize(QtCore.QSize(650, 300))
        win_about.setMaximumSize(QtCore.QSize(650, 300))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        win_about.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/插图/N.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        win_about.setWindowIcon(icon)
        win_about.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(win_about)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(win_about)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(50, 40, 150, 150))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(80, 80))
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setPixmap(QtGui.QPixmap(":/插图/logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(240, 20, 361, 191))
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(win_about)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 6)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(win_about)
        self.pushButton.clicked.connect(win_about.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(win_about)

    def retranslateUi(self, win_about):
        _translate = QtCore.QCoreApplication.translate
        win_about.setWindowTitle(_translate("win_about", "关于"))
        self.label_3.setText(_translate("win_about", "<html><head/><body><p><span style=\" font-size:14pt; color:#000000;\">Nonlinear MDOF time history analysis<br/>非线性多自由度时程分析软件</span></p><p><span style=\" font-size:14pt; color:#000000;\">Copyright (c) date<br/>开发者：列文琛<br/>版本：Version<br/>联系邮箱：438171766@qq.com<br/>QQ：438171766</span></p></body></html>"))
        self.pushButton.setText(_translate("win_about", "确认"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    win_about = QtWidgets.QDialog()
    ui = Ui_win_about()
    ui.setupUi(win_about)
    win_about.show()
    sys.exit(app.exec_())
