# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Projects\NLMDOF\ui\win_tcl_file.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_win_tcl_file(object):
    def setupUi(self, win_tcl_file):
        win_tcl_file.setObjectName("win_tcl_file")
        win_tcl_file.resize(980, 641)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        win_tcl_file.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/插图/N.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        win_tcl_file.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(win_tcl_file)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(win_tcl_file)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(win_tcl_file)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(win_tcl_file)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(win_tcl_file)
        self.pushButton_2.clicked.connect(win_tcl_file.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(win_tcl_file)

    def retranslateUi(self, win_tcl_file):
        _translate = QtCore.QCoreApplication.translate
        win_tcl_file.setWindowTitle(_translate("win_tcl_file", "tcl代码"))
        self.textEdit.setHtml(_translate("win_tcl_file", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("win_tcl_file", "复制"))
        self.pushButton_2.setText(_translate("win_tcl_file", "确认"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    win_tcl_file = QtWidgets.QDialog()
    ui = Ui_win_tcl_file()
    ui.setupUi(win_tcl_file)
    win_tcl_file.show()
    sys.exit(app.exec_())
