# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Projects\NLMDOF\ui\win_run.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_win_run(object):
    def setupUi(self, win_run):
        win_run.setObjectName("win_run")
        win_run.resize(400, 187)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        win_run.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/插图/N.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        win_run.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(win_run)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(win_run)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(win_run)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 4, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.progressBar = QtWidgets.QProgressBar(win_run)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 40))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pushButton = QtWidgets.QPushButton(win_run)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(win_run)
        QtCore.QMetaObject.connectSlotsByName(win_run)

    def retranslateUi(self, win_run):
        _translate = QtCore.QCoreApplication.translate
        win_run.setWindowTitle(_translate("win_run", "正在运行..."))
        self.label.setText(_translate("win_run", "求解进度：（请勿关闭该窗口）"))
        self.label_2.setText(_translate("win_run", "正在计算第xx条地震动（共xx条）"))
        self.pushButton.setText(_translate("win_run", "中断分析"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    win_run = QtWidgets.QDialog()
    ui = Ui_win_run()
    ui.setupUi(win_run)
    win_run.show()
    sys.exit(app.exec_())
