# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Projects\NLMDOF\ui\win_export.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_win_export(object):
    def setupUi(self, win_export):
        win_export.setObjectName("win_export")
        win_export.resize(235, 88)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        win_export.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/插图/N.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        win_export.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(win_export)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(win_export)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(win_export)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(win_export)
        self.pushButton_2.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(win_export)
        QtCore.QMetaObject.connectSlotsByName(win_export)

    def retranslateUi(self, win_export):
        _translate = QtCore.QCoreApplication.translate
        win_export.setWindowTitle(_translate("win_export", "导出所有数据"))
        self.label.setText(_translate("win_export", "请选择导出格式："))
        self.pushButton.setText(_translate("win_export", ".txt"))
        self.pushButton_2.setText(_translate("win_export", ".xlsx"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    win_export = QtWidgets.QDialog()
    ui = Ui_win_export()
    ui.setupUi(win_export)
    win_export.show()
    sys.exit(app.exec_())
