# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Projects\NLMDOF\ui\win_scale.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_win_scale(object):
    def setupUi(self, win_scale):
        win_scale.setObjectName("win_scale")
        win_scale.resize(300, 214)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(win_scale.sizePolicy().hasHeightForWidth())
        win_scale.setSizePolicy(sizePolicy)
        win_scale.setMinimumSize(QtCore.QSize(300, 200))
        win_scale.setMaximumSize(QtCore.QSize(300, 214))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        win_scale.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/插图/N.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        win_scale.setWindowIcon(icon)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(win_scale)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(win_scale)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_2.addWidget(self.radioButton_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout_2.addWidget(self.radioButton_5)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout_4.addWidget(self.radioButton_6)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton.setCheckable(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout_3.setStretch(0, 5)

        self.retranslateUi(win_scale)
        self.pushButton_2.clicked.connect(win_scale.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(win_scale)

    def retranslateUi(self, win_scale):
        _translate = QtCore.QCoreApplication.translate
        win_scale.setWindowTitle(_translate("win_scale", "缩放"))
        self.groupBox_2.setTitle(_translate("win_scale", "缩放所有地震动"))
        self.radioButton_4.setText(_translate("win_scale", "归一化"))
        self.radioButton_5.setText(_translate("win_scale", "指定PGA(g)："))
        self.lineEdit.setText(_translate("win_scale", "0.4"))
        self.radioButton_6.setText(_translate("win_scale", "指定缩放系数："))
        self.lineEdit_4.setText(_translate("win_scale", "1"))
        self.pushButton.setText(_translate("win_scale", "确认"))
        self.pushButton_2.setText(_translate("win_scale", "返回"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    win_scale = QtWidgets.QDialog()
    ui = Ui_win_scale()
    ui.setupUi(win_scale)
    win_scale.show()
    sys.exit(app.exec_())
