# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Projects\NLMDOF\ui\win_mass.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_win_mass(object):
    def setupUi(self, win_mass):
        win_mass.setObjectName("win_mass")
        win_mass.resize(402, 523)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        win_mass.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/插图/N.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        win_mass.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(win_mass)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(win_mass)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableWidget = QtWidgets.QTableWidget(win_mass)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(win_mass)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(win_mass)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(win_mass)
        QtCore.QMetaObject.connectSlotsByName(win_mass)

    def retranslateUi(self, win_mass):
        _translate = QtCore.QCoreApplication.translate
        win_mass.setWindowTitle(_translate("win_mass", "定义质量"))
        self.label.setText(_translate("win_mass", "请输入各层质量（单位：吨）："))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("win_mass", "楼层"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("win_mass", "质量 [t]"))
        self.pushButton.setText(_translate("win_mass", "确认"))
        self.pushButton_2.setText(_translate("win_mass", "返回"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    win_mass = QtWidgets.QDialog()
    ui = Ui_win_mass()
    ui.setupUi(win_mass)
    win_mass.show()
    sys.exit(app.exec_())
