# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Projects\NLMDOF\ui\win_mat.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_win_mat(object):
    def setupUi(self, win_mat):
        win_mat.setObjectName("win_mat")
        win_mat.resize(350, 266)
        win_mat.setMinimumSize(QtCore.QSize(350, 266))
        win_mat.setMaximumSize(QtCore.QSize(350, 266))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        win_mat.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/插图/N.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        win_mat.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(win_mat)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(win_mat)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(win_mat)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.lineEdit_5 = QtWidgets.QLineEdit(win_mat)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_5.setInputMask("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_2.addWidget(self.lineEdit_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(win_mat)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(win_mat)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(win_mat)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(win_mat)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(win_mat)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(win_mat)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(win_mat)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(win_mat)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(win_mat)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(win_mat)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(win_mat)
        QtCore.QMetaObject.connectSlotsByName(win_mat)

    def retranslateUi(self, win_mat):
        _translate = QtCore.QCoreApplication.translate
        win_mat.setWindowTitle(_translate("win_mat", "定义备选材料"))
        self.label.setText(_translate("win_mat", "材料类型："))
        self.label_6.setText(_translate("win_mat", "备注名："))
        self.label_2.setText(_translate("win_mat", "参数1（xx）："))
        self.label_3.setText(_translate("win_mat", "参数2（xx）："))
        self.label_4.setText(_translate("win_mat", "参数3（xx）："))
        self.label_5.setText(_translate("win_mat", "参数4（xx）："))
        self.pushButton.setText(_translate("win_mat", "确认"))
        self.pushButton_2.setText(_translate("win_mat", "返回"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    win_mat = QtWidgets.QDialog()
    ui = Ui_win_mat()
    ui.setupUi(win_mat)
    win_mat.show()
    sys.exit(app.exec_())
