# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Projects\NLMDOF\ui\win_terminal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_win_terminal(object):
    def setupUi(self, win_terminal):
        win_terminal.setObjectName("win_terminal")
        win_terminal.setWindowModality(QtCore.Qt.ApplicationModal)
        win_terminal.resize(818, 641)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        win_terminal.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/插图/N.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        win_terminal.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(win_terminal)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(win_terminal)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.textEdit.setFont(font)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(win_terminal)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(win_terminal)
        self.pushButton_2.clicked.connect(win_terminal.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(win_terminal)

    def retranslateUi(self, win_terminal):
        _translate = QtCore.QCoreApplication.translate
        win_terminal.setWindowTitle(_translate("win_terminal", "终端输出"))
        self.textEdit.setHtml(_translate("win_terminal", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\',\'Times New Roman\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p></body></html>"))
        self.pushButton_2.setText(_translate("win_terminal", "返回"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    win_terminal = QtWidgets.QDialog()
    ui = Ui_win_terminal()
    ui.setupUi(win_terminal)
    win_terminal.show()
    sys.exit(app.exec_())
